// ===----------------------------------------------------------------------===//
//
// Copyright (c) 2025 Coen ten Thije Boonkkamp
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of project contributors
//
// SPDX-License-Identifier: Apache-2.0
//
// ===----------------------------------------------------------------------===//

public import WHATWG_HTML_Shared

/// Represents an HTML Sample Output element (`<samp>`), which is used to enclose inline text
/// that represents sample (or quoted) output from a computer program.
///
/// The `Samp` element's contents are typically rendered using the browser's default monospaced font
/// (such as Courier or Lucida Console).
///
/// ## Example
///
/// ```swift
/// samp {
///     "Keyboard not found"
///     br {}
///     "Press F1 to continue"
/// }
/// ```
///
/// ## Best Practices
///
/// - Use `<samp>` to represent output from a computer program or system.
/// - Can be nested with other elements like `<kbd>` to represent user input within sample output.
/// - Use CSS to override the default font face if necessary, though browser preferences may take precedence.
/// - For output generated by your website's JavaScript code, consider using the `<output>` element instead.
///
public struct Samp: WHATWG_HTML.Element.`Protocol` {
    /// The HTML tag name
    @inlinable public static var tag: String { "samp" }
    public static let categories: Set<WHATWG_HTML.Element.Content.Category> = [
        .flow, .phrasing, .palpable,
    ]
    public static let content: WHATWG_HTML.Element.Content = .init(model: .categories([.phrasing]))

    /// Creates a new Sample Output element with the specified content.
    public init(

        )
    {

    }
}
